# Generated by Django 5.1.7 on 2025-03-12 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_mgnt', '0003_myproject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myproject',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='projects/'),
        ),
    ]
