# Generated by Django 5.1.7 on 2025-03-12 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_mgnt', '0004_alter_myproject_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myproject',
            name='demo_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='myproject',
            name='git_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='myproject',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='projects/'),
        ),
    ]
