# Generated by Django 5.1.7 on 2025-03-14 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_mgnt', '0005_alter_myproject_demo_link_alter_myproject_git_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myproject',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
