# Generated by Django 5.1.7 on 2025-03-16 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_mgnt', '0006_alter_myproject_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myproject',
            name='project_title',
            field=models.CharField(max_length=225),
        ),
    ]
