# Generated by Django 5.1.7 on 2025-03-21 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_mgnt', '0007_alter_myproject_project_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myproject',
            name='demo_link',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='myproject',
            name='git_link',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='myproject',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='projects/'),
        ),
        migrations.AlterField(
            model_name='myproject',
            name='project_title',
            field=models.CharField(max_length=200),
        ),
    ]
