# Generated by Django 5.1.7 on 2025-03-21 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_mgnt', '0008_alter_myproject_demo_link_alter_myproject_git_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myproject',
            name='demo_link',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='myproject',
            name='git_link',
            field=models.URLField(blank=True),
        ),
    ]
