# Generated by Django 5.1.7 on 2025-03-21 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_mgnt', '0009_alter_myproject_demo_link_alter_myproject_git_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Technologies',
            },
        ),
        migrations.AddField(
            model_name='myproject',
            name='technologies',
            field=models.CharField(default='', help_text='Enter technologies separated by commas (e.g., React, Node.js, MongoDB)', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='myproject',
            name='demo_link',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='myproject',
            name='git_link',
            field=models.URLField(),
        ),
    ]
