# Generated by Django 5.1.7 on 2025-03-21 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_mgnt', '0010_technology_myproject_technologies_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myproject',
            name='technologies',
            field=models.CharField(blank=True, help_text='Enter technologies separated by commas (e.g., React, Node.js, MongoDB)', max_length=500, null=True),
        ),
    ]
