# Generated by Django 5.1.7 on 2025-03-24 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_mgnt', '0017_herosection'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThemeSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_color', models.CharField(default='#0d6efd', help_text='Primary theme color (e.g., #0d6efd)', max_length=7)),
                ('secondary_color', models.CharField(default='#6c757d', help_text='Secondary theme color', max_length=7)),
                ('accent_color', models.CharField(default='#240303', help_text='Accent color for highlights', max_length=7)),
                ('background_color', models.CharField(default='#ffffff', help_text='Main background color', max_length=7)),
                ('section_bg_light', models.CharField(default='#f8f9fa', help_text='Light section background', max_length=7)),
                ('section_bg_dark', models.CharField(default='#212529', help_text='Dark section background', max_length=7)),
                ('text_color_light', models.CharField(default='#ffffff', help_text='Light text color', max_length=7)),
                ('text_color_dark', models.CharField(default='#212529', help_text='Dark text color', max_length=7)),
                ('heading_font', models.CharField(default="'Poppins', sans-serif", help_text="Font family for headings (e.g., 'Poppins', sans-serif)", max_length=100)),
                ('body_font', models.CharField(default="'Open Sans', sans-serif", help_text='Font family for body text', max_length=100)),
                ('heading_size', models.CharField(default='2.5rem', help_text='Size for main headings (e.g., 2.5rem)', max_length=10)),
                ('subheading_size', models.CharField(default='1.8rem', help_text='Size for sub-headings', max_length=10)),
                ('body_size', models.CharField(default='1rem', help_text='Size for body text', max_length=10)),
            ],
            options={
                'verbose_name': 'Theme Settings',
                'verbose_name_plural': 'Theme Settings',
            },
        ),
    ]
