# Generated by Django 5.1.7 on 2025-03-24 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_mgnt', '0018_themesettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(help_text='URL-friendly version of the title', unique=True)),
                ('summary', models.TextField(help_text='A brief summary of the blog post')),
                ('content', models.TextField()),
                ('image', models.ImageField(help_text='Cover image for the blog post', upload_to='blog/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=True)),
                ('read_time', models.IntegerField(default=5, help_text='Estimated reading time in minutes')),
            ],
            options={
                'verbose_name': 'Blog Post',
                'verbose_name_plural': 'Blog Posts',
                'ordering': ['-created_at'],
            },
        ),
    ]
